version: '3'

services:
  db:
    image: postgres:10
    restart: always
    environment:
     POSTGRES_DB: ${DB}
     POSTGRES_USER: ${USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5434:5432
#    volumes:
#      - ./postgres-data/postgres:/var/lib/postgresql/data

  u-mts:
    restart: always
    build: .
    volumes:
      - .:/u-mts
    depends_on:
      - db
    command: python run.py run
    env_file:
        - .env
    ports:
      - 5000:5000


  adminer:
      image: adminer
      restart: always
      ports:
          - 8080:8080


